import type { VisualAssetEntry } from '@/presentation/assets/visual-asset-types';

const MAIN_MENU_BASE = '/assets/main-menu';
const CHARTS_BASE = '/assets/charts';

function entry(
  partial: Omit<VisualAssetEntry, 'fallbackId'> & { readonly fallbackId?: string | null },
): VisualAssetEntry {
  return Object.freeze({
    fallbackId: null,
    ...partial,
  });
}

/** Central registry for all approved visual assets (Phase 4C). */
export const VISUAL_ASSET_REGISTRY: Readonly<Record<string, VisualAssetEntry>> = Object.freeze({
  // Category A — Main menu runtime backgrounds
  'MM-001': entry({
    id: 'MM-001',
    label: 'Main Menu Background',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-001.png`,
    theme: 'any',
    priority: 'critical',
    preload: true,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-001_Main_Menu_Final.png',
    runtimeComponent: 'MainMenuScreen',
    notes: 'Decorative background only — UI text rendered in React.',
  }),
  'MM-002': entry({
    id: 'MM-002',
    label: 'New Game Panel Reference',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-002.png`,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-002_New_Game_Dialog_v1.png',
    runtimeComponent: 'NewGamePanel',
    notes: 'Layout reference; panel uses React form controls.',
  }),
  'MM-003': entry({
    id: 'MM-003',
    label: 'Load Game Panel Reference',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-003.png`,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-003_Load_Game_v1.png',
    runtimeComponent: 'LoadGamePanel',
    notes: 'Layout reference; save list rendered dynamically.',
  }),
  'MM-004': entry({
    id: 'MM-004',
    label: 'Settings Panel Reference',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-004.png`,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-004_Settings_v1.png',
    runtimeComponent: 'SettingsPanel',
    notes: 'Layout reference; settings bound to theme + localStorage.',
  }),
  'MM-005': entry({
    id: 'MM-005',
    label: 'Credits Panel Reference',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-005.png`,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-005_Credits.png.png',
    runtimeComponent: 'CreditsPanel',
    notes: 'Layout reference; credits text from menu-credits-data.',
  }),
  'MM-006': entry({
    id: 'MM-006',
    label: 'Splash Screen Background',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-006.png`,
    theme: 'any',
    priority: 'critical',
    preload: true,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-006_Splash.png',
    runtimeComponent: 'SplashScreen',
    notes: 'Startup splash background with React branding overlay.',
  }),
  'MM-007': entry({
    id: 'MM-007',
    label: 'Loading Screen Background',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-007.png`,
    theme: 'any',
    priority: 'critical',
    preload: true,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-007_Loading.png',
    runtimeComponent: 'MenuLoadingScreen',
    notes: 'Loading phase background while session status is fetched.',
  }),
  'BR-001': entry({
    id: 'BR-001',
    label: 'Project Genesis Brand Mark',
    category: 'runtime',
    path: `${MAIN_MENU_BASE}/MM-006.png`,
    theme: 'any',
    priority: 'high',
    preload: true,
    fallbackId: null,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/MM-006_Splash.png',
    runtimeComponent: 'SplashScreen',
    notes: 'Brand mark sourced from splash art until dedicated logo asset exists.',
  }),

  // Category B — Dashboard mockup references (PG components render runtime UI)
  'DB-001': entry({
    id: 'DB-001',
    label: 'Executive Dashboard Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-001_Executive_Dashboard.png',
    runtimeComponent: 'ExecutiveDashboardScreen',
    notes: 'Reference only — rendered by PG dashboard grid + charts.',
  }),
  'DB-002': entry({
    id: 'DB-002',
    label: 'KPI Cards Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-002_KPI_Cards.png',
    runtimeComponent: 'PGKpiCard',
    notes: null,
  }),
  'DB-003': entry({
    id: 'DB-003',
    label: 'Status Panel Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-003_Status_Panel.png',
    runtimeComponent: 'PGStatusPanel',
    notes: null,
  }),
  'DB-004': entry({
    id: 'DB-004',
    label: 'Notifications Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-004_Notifications.png',
    runtimeComponent: 'PGNotificationCenter',
    notes: null,
  }),
  'DB-005': entry({
    id: 'DB-005',
    label: 'Finance Widget Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-005_Finance_Widget.png',
    runtimeComponent: 'PGFinanceWidget',
    notes: null,
  }),
  'DB-006': entry({
    id: 'DB-006',
    label: 'Production Widget Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-006_Production_Widget.png',
    runtimeComponent: 'PGProductionWidget',
    notes: null,
  }),
  'DB-007': entry({
    id: 'DB-007',
    label: 'Research Widget Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-007_Research_Widget.png',
    runtimeComponent: 'PGResearchWidget',
    notes: null,
  }),
  'DB-008': entry({
    id: 'DB-008',
    label: 'Supply Chain Widget Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-008_Transport_Widget.png',
    runtimeComponent: 'PGSupplyChainWidget',
    notes: null,
  }),
  'DB-009': entry({
    id: 'DB-009',
    label: 'Company Overview Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-009_Company_Overview.png',
    runtimeComponent: 'PGCompanyWidget',
    notes: null,
  }),
  'DB-010': entry({
    id: 'DB-010',
    label: 'Dashboard Report Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/Mockups/dashboard/DB-010_Dashboard.png',
    runtimeComponent: 'PGReportWidget',
    notes: null,
  }),

  // Category C — SVG runtime
  'CH-010': entry({
    id: 'CH-010',
    label: 'Chart Style Reference SVG',
    category: 'svg-runtime',
    path: `${CHARTS_BASE}/CH-010_Charts.svg`,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/Bilder/einzelne_bilder/hochgeladen/CH-010_Charts.svg',
    runtimeComponent: 'PGChartWidget',
    notes: 'Style reference; charts render via Recharts + design tokens.',
  }),
  'WM-SVG-GRID': entry({
    id: 'WM-SVG-GRID',
    label: 'World Grid Overlay',
    category: 'svg-runtime',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: null,
    runtimeComponent: 'PGWorldCanvas',
    notes: 'Procedural SVG grid layer — token-driven stroke.',
  }),
  'WM-SVG-LEGEND': entry({
    id: 'WM-SVG-LEGEND',
    label: 'World Legend Swatches',
    category: 'svg-runtime',
    path: null,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: null,
    runtimeComponent: 'PGWorldLegend',
    notes: 'CSS swatch legend bound to active map layers.',
  }),

  // Category B — World mockups (planned, no PNG on disk yet)
  'WM-001': entry({
    id: 'WM-001',
    label: 'World Map Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'high',
    preload: false,
    designSource: 'docs/design/mockups/world/WM-001_World_Map.png',
    runtimeComponent: 'PGWorldCanvas',
    notes: 'Planned mockup — runtime uses procedural SVG map (Phase 4A/4B).',
  }),
  'WM-002': entry({
    id: 'WM-002',
    label: 'Region View Mockup',
    category: 'reference',
    path: null,
    theme: 'any',
    priority: 'normal',
    preload: false,
    designSource: 'docs/design/mockups/world/WM-002_Region_View.png',
    runtimeComponent: 'PGWorldInspector',
    notes: 'Planned mockup — inspector uses PGInspectorPanel sections.',
  }),
});

export const RUNTIME_VISUAL_ASSET_IDS = Object.freeze(
  Object.values(VISUAL_ASSET_REGISTRY)
    .filter((asset) => asset.category === 'runtime' && asset.path !== null)
    .map((asset) => asset.id),
);

export const PRELOAD_VISUAL_ASSET_IDS = Object.freeze(
  Object.values(VISUAL_ASSET_REGISTRY)
    .filter((asset) => asset.preload && asset.path !== null)
    .map((asset) => asset.id),
);

export function getVisualAssetEntry(assetId: string): VisualAssetEntry | null {
  return VISUAL_ASSET_REGISTRY[assetId] ?? null;
}

export function listVisualAssetsByCategory(
  category: VisualAssetEntry['category'],
): readonly VisualAssetEntry[] {
  return Object.freeze(
    Object.values(VISUAL_ASSET_REGISTRY).filter((asset) => asset.category === category),
  );
}
