export { PGKpiCard, type PGKpiCardVariant } from './PGKpiCard';
export { PGStatusPanel, type PGStatusPanelItem } from './PGStatusPanel';
export { PGNotificationCenter, type PGNotificationItem } from './PGNotificationCenter';
export { PGFinanceWidget, type PGFinanceRow } from './PGFinanceWidget';
export { PGProductionWidget, type PGProductionRow } from './PGProductionWidget';
export { PGResearchWidget, type PGResearchRow } from './PGResearchWidget';
export { PGSupplyChainWidget, type PGSupplyChainRow } from './PGSupplyChainWidget';
export { PGCompanyWidget, type PGCompanySummaryRow, type PGRegionalPresenceRow } from './PGCompanyWidget';
export { PGReportWidget, type PGReportAction } from './PGReportWidget';
export { PGOperationsTable, type PGOperationsTableRow } from './PGOperationsTable';
export { PGMarketTrendBadge, type PGMarketTrend } from './PGMarketTrendBadge';
export { PGBuildingsWidget } from './PGBuildingsWidget';
export { PGEmployeesWidget } from './PGEmployeesWidget';
export { PGEconomyWidget } from './PGEconomyWidget';
export { PGMarketWidget } from './PGMarketWidget';
export { PGInventoryWidget, type PGInventoryWarehouseBlock } from './PGInventoryWidget';
export { PGTutorialPanel } from './PGTutorialPanel';
export * from './charts';
